hw1 first attempt
crossopt/Java-HW pull request #1
Opened 2019-01-20 17:15 UTC by crossopt

2019-01-27 17:35 UTC, jzuken requested changes

2019-01-27 17:35 UTC, jzuken commented on HashTable/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
этот файл тоже не надо выкладывать, это настройки редактора

2019-01-27 17:35 UTC, jzuken commented on HashTable/build.gradle
> +sourceCompatibility = 1.8
лучше всё же пользоваться 11-й версией

2019-01-27 17:35 UTC, jzuken commented on HashTable/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-bin.zip
и gradle тогда тоже нужен будет пятый

2019-01-27 17:35 UTC, jzuken commented on HashTable/src/main/java/ru/hse/crossopt/HashTable/HashTable.java
> +        return ((key.hashCode() % capacity) + capacity) % capacity;
как-то слишком хитро. можно было просто модуль хешкода взять

2019-01-27 17:35 UTC, jzuken commented on HashTable/src/main/java/ru/hse/crossopt/HashTable/HashTable.java
> +    /**
однострочные доки лучше так и писать в одну строку: `/** ... */`

2019-01-27 17:35 UTC, jzuken commented on HashTable/src/main/java/ru/hse/crossopt/HashTable/HashTable.java
> +    public String put(String key, String value) {
а аргументы вполне могут быть null

2019-01-27 17:35 UTC, jzuken commented on HashTable/src/main/java/ru/hse/crossopt/HashTable/List.java
> +
одной пустой строки тут вполне достаточно

2019-01-27 17:35 UTC, jzuken commented on HashTable/src/main/java/ru/hse/crossopt/HashTable/List.java
> +        head = new Node(null, null);
это можно было сделать сразу при объявлении

2019-01-27 19:51 UTC, crossopt commented on HashTable/src/main/java/ru/hse/crossopt/HashTable/HashTable.java
> +    public String put(String key, String value) {
Не вижу проблемы, я предполагала, что хеш-таблица будет уметь работать с null-ами.
put положит в хеш-таблицу значение value по ключу key и вернуть то, что было по этому ключу раньше, либо null, если ничего не было. 
Если key null, оно отработает. Если раньше по этому ключу лежал null, он вернет null, чего уж там. Программист может различить, действительно ли по этому ключу лежат value null, например с помощью contains.

2019-01-28 19:02 UTC, jzuken requested changes

2019-01-28 19:02 UTC, jzuken commented on HashTable/src/main/java/ru/hse/crossopt/HashTable/HashTable.java
> +    public String put(String key, String value) {
давайте просто запретим класть null в таблицу и будем кидать в этом месте IllegalArgumentException

2019-02-11 15:45 UTC, merged