hw7 first attempt
crossopt/Java-HW pull request #10
Opened 2019-04-13 18:23 UTC by crossopt

2019-05-02 09:24 UTC, jzuken requested changes

2019-05-02 09:24 UTC, jzuken commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> +        wasShutdown = true;
а ещё join() не помешал бы

2019-05-02 09:24 UTC, jzuken commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> +        return task;
идея тут ругается на unchecked assignment

2019-05-02 09:24 UTC, jzuken commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> +    @NotNull public <T> LightFuture<T> add(@NotNull Supplier<T> supplier) {
а тут тоже, видимо, надо на wasShutdown проверять

2019-05-04 09:52 UTC, crossopt commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> +    @NotNull public <T> LightFuture<T> add(@NotNull Supplier<T> supplier) {
А зачем? submit все проверит

2019-05-04 09:53 UTC, crossopt commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> +    @NotNull public <T> LightFuture<T> add(@NotNull Supplier<T> supplier) {
Ну мб ради читаемости кода, ок

2019-05-04 10:38 UTC, crossopt commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> +        return task;
А у меня не ругается. Это какие-то настройки надо подкрутить?

2019-05-05 06:01 UTC, jzuken commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> +        return task;
стандартные статические анализаторы идеи вроде бы. у меня 2019.1.1

2019-05-11 09:43 UTC, jzuken requested changes

2019-05-11 09:43 UTC, jzuken commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> -            thread.interrupt();
не, interrupt то вы зря удалили. как потоки узнают, что им надо завершаться?

2019-05-11 09:48 UTC, crossopt commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> -            thread.interrupt();
Не удалила, а там на стримы переписала для красоты

2019-05-11 14:43 UTC, jzuken commented on ThreadPool/src/main/java/ru/hse/crossopt/ThreadPool/ThreadPool.java
> -            thread.interrupt();
а, сорян. не заметил

2019-05-11 14:43 UTC, merged