Hw8
crossopt/Java-HW pull request #12
Opened 2019-05-22 01:30 UTC by crossopt

2019-05-30 19:47 UTC, RamSaw requested changes
@crossopt написал пару комментов. В целом все ок. Вас тесты не просили писать?
пофиксите еще конфликты с мастером, пожалуйста.

2019-05-30 19:47 UTC, RamSaw commented on Cannon/build.gradle
> +mainClassName = 'ru.hse.crossopt.Cannon.CannonGame'
jar не запускается

2019-05-30 19:47 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Cannon.java
> +    private int bulletType = 1;
enum лучше

2019-05-30 19:47 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Cannon.java
> +        checkArgument(1 <= type && type <= LARGEST_BULLET, "Bullet size out of range.");
так type или size?

2019-05-30 19:47 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Cannon.java
> +            return (int)(yOriginal + getSpeed() * time * Math.sin(angle) - GRAVITY * time * time);
ура, нормальное физическое уравнение :) респект

2019-05-30 19:47 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Drawer.java
> + * Not related to furniture.
furniture?

2019-05-30 19:47 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Drawer.java
> +        var newX = Arrays.stream(xCoordinates).mapToDouble(this::convertXPoint).toArray();
а зачем быть в интах, если JavaFX принимает double?

2019-05-30 19:47 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Landscape.java
> +        return 0;
я бы наверное Exception бросал. Такого же с текущей логикой игры быть не должно.

2019-05-30 19:47 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Landscape.java
> +                Landscape.WIDTH / 10, Landscape.HEIGHT * 9 / 10, Color.BLACK);
мб выделим эти константы (да и выше тоже можно) в переменные типа widthProportionForInstructions

2019-05-30 19:47 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Landscape.java
> +            return getYForX(x) + 3 * radius >= y || getYForX(x + radius) + 2 * radius >= y;
почему 3 и 2?

2019-05-31 17:10 UTC, crossopt commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Cannon.java
> +        checkArgument(1 <= type && type <= LARGEST_BULLET, "Bullet size out of range.");
Скорее size.
Назову bulletRadius, чтобы совсем понятно было. И тогда без enum'ов, да? Потому что радиус по смыслу число

2019-05-31 17:14 UTC, crossopt commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Drawer.java
> +        var newX = Arrays.stream(xCoordinates).mapToDouble(this::convertXPoint).toArray();
Ну, мне слишком часто в детстве говорили ни в коем случае не пользоваться действительными числами:)
Принципиально хочется все внутренние вычисления хранить в интах и переводить только для вывода в Drawer'e, потому что точность мне не очень важна, а даблы заставляют задумываться об сравнениях с эпсилонами и провей радости.
Кажется, просто хранить целочисленные координаты проще

2019-05-31 17:24 UTC, crossopt commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Landscape.java
> +        return 0;
А зачем? В текущей логике игры пуля может вылететь за границу гор.
Без того, чтобы лезть в код не вспомнила, что такого быть не должно (при проверке того, что снаряд не взорвался, я сначала проверяю, что он не вылетел за границу поля, а только потом вызываю этот метод).
Но я совершенно не против, чтобы мой код считал, что за видимым куском гор идет равнина без гор и адекватно это обрабатывал.

2019-05-31 17:34 UTC, crossopt commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Landscape.java
> +            return getYForX(x) + 3 * radius >= y || getYForX(x + radius) + 2 * radius >= y;
Логика была в том, чтобы избежать лишних уравнений и проверить, что пуля находится достаточно близко к стороне горы.
Что константы разные пофикшу.

2019-05-31 17:37 UTC, crossopt commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Drawer.java
> + * Not related to furniture.
Проверяющие читают javadoc'и??
Убрала

2019-06-04 11:53 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Drawer.java
> +        var newX = Arrays.stream(xCoordinates).mapToDouble(this::convertXPoint).toArray();
ок, звучит как аргумент.

2019-06-04 11:55 UTC, RamSaw commented on Cannon/src/main/java/ru/hse/crossopt/Cannon/Landscape.java
> +        return 0;
ок

2019-06-04 12:07 UTC, RamSaw approved these changes
@crossopt все ок.
@jzuken

2019-06-06 08:15 UTC, merged