Hw9
crossopt/Java-HW pull request #14
Opened 2019-05-31 17:00 UTC by crossopt

2019-06-07 17:06 UTC, jzuken requested changes

2019-06-07 17:06 UTC, jzuken commented on MyJUnit/src/test/java/ru/hse/crossopt/myjunit/TestRunnerTest.java
> +class TestRunnerTest {
не надо использовать платфомо-зависимые переводы строк в коде.
-0.5

> Task :test FAILED

ru.hse.crossopt.myjunit.TestRunnerTest > testAllMethodsInOneClassRun() FAILED
    org.opentest4j.AssertionFailedError at TestRunnerTest.java:73

8 tests completed, 1 failed

FAILURE: Build failed with an exception.

2019-06-07 17:06 UTC, jzuken commented on MyJUnit/src/main/java/ru/hse/crossopt/myjunit/TestRunner.java
> +        ArrayList<Method> beforeClassMethods = new ArrayList<>();
слева лучше обобщённый интерфейс использовать

2019-06-07 17:06 UTC, jzuken commented on MyJUnit/src/main/java/ru/hse/crossopt/myjunit/TestRunner.java
> +            int foundMethods = 0;
foundAnnotations?

2019-06-10 08:54 UTC, jzuken commented
а теперь два теста не проходит:

> Task :test FAILED

ru.hse.crossopt.myjunit.TestRunnerTest > testAllMethodsInOneClassRun() FAILED
    org.opentest4j.AssertionFailedError at TestRunnerTest.java:99

ru.hse.crossopt.myjunit.TestRunnerTest > testIgnoreOneTest() FAILED
    org.opentest4j.AssertionFailedError at TestRunnerTest.java:99

8 tests completed, 2 failed

2019-06-10 09:07 UTC, crossopt commented
> а а теперь два теста не проходят:
> 
> > Task :test FAILED
> 
> ru.hse.crossopt.myjunit.TestRunnerTest > testAllMethodsInOneClassRun() FAILED
> org.opentest4j.AssertionFailedError at TestRunnerTest.java:99
> 
> ru.hse.crossopt.myjunit.TestRunnerTest > testIgnoreOneTest() FAILED
> org.opentest4j.AssertionFailedError at TestRunnerTest.java:99
> 
> 8 tests completed, 2 failed
> 
> -1

Ммм, это все еще Винда?
И у меня на системе все работает, и Трэвис говорит, что тесты прошли.

2019-06-10 10:57 UTC, jzuken commented
ага. захарддоженные переводы строки это плохо

2019-06-10 11:03 UTC, merged